#!/bin/sh

set -e
set -x

export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
sudo apt-get install -y -q git \
cmake \
clang clang-3.6 \
libxrandr-dev \
libsm-dev \
libqt4-dev \
qtmobility-dev \
libkml-dev \
liburiparser-dev \
libgdal-dev \
libsqlite3-dev \
libtiff5-dev \
libssl-dev \
liblog4cxx10-dev \
libbz2-dev \
libpng12-dev \
kdelibs5-dev \
libglib2.0-dev \
libgif-dev \
libgeotiff-dev \
libgeos-dev \
libgeos++-dev \
libavcodec-dev \
libavdevice-dev \
libavfilter-dev \
libavformat-dev \
libavutil-dev \
libpostproc-dev \
libswscale-dev \
libexpat1-dev \
libcurl4-gnutls-dev \
libaprutil1-dev \
libapr1-dev \
nsis \
perl \
python3-dev \
p7zip-full \
zlib1g-dev \
libfreetype6-dev \
libprotobuf-dev \
protobuf-compiler \
libpion-net-dev \
liblog4cpp5-dev \
liblog4cplus-dev \
libqca2-dev \
libqca2-plugin-cyrus-sasl \
libkrb5-dev \
libusb-1.0-0-dev \
libv8-dev \
libcolladadom-dev \
libshp-dev \
libdisasm-dev \
libssh2-1-dev \
libportaudio2 \
libgraphviz-dev \
librrd-dev \
libvlc-dev \
libvrpn-dev \
libleveldb-dev \
libnvtt-dev \
libxml2-dev \
libxslt1-dev \
libgrantlee5-dev \
qtbase5-dev \
qtbase5-dev-tools \
libqt5opengl5-dev \
qttools5-dev-tools \
qttools5-dev \
qtscript5-dev \
libqt5svg5-dev \
libqt5xmlpatterns5-dev \
libqt5serialport5-dev \
qtmultimedia5-dev \
qtdeclarative5-dev \
libkf5xmlgui-dev \
libkf5texteditor-dev \
libkf5khtml-dev \
libquazip-qt5-dev \
python3-pyaudio \
libboost-date-time1.55-dev \
libboost-filesystem1.55-dev \
libboost-system1.55-dev \
libboost-thread1.55-dev \
libboost1.55-dev \
libboost-serialization1.55-dev \
libboost-atomic1.55-dev \
libboost-chrono1.55-dev \
libboost-regex1.55-dev \
libboost-test1.55-dev
